title: "Jiajun Liang"
description: "Former QA engineer writing about code, markets, travel, and systems."
url: "https://jackmeson1.github.io"
baseurl: ""

remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/default.css"

locale: "en"
timezone: "America/Vancouver"
permalink: /:categories/:year/:month/:day/:title/
paginate: 8
paginate_path: "/posts/page:num/"
search: true

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

author:
  name: "Jiajun Liang"
  picture: "/assets/images/avatar.jpg"
  bio: "Former QA engineer writing about code, markets, travel, and systems."
  location: "Vancouver, BC"


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
