# Site metadata
title: Financial Analysis Lab
description: Deep Financial Research | AI & Industry Insights | Data-Driven Perspectives
author: Jackmeson
email: your-email@example.com
baseurl: ""
url: "https://jackmeson1.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation menu
header_pages:
  - index.md
  - about.md
  - archive.md

# Pagination settings
paginate: 10
paginate_path: "/page:num/"

# Social profiles (optional)
github_username: jackmeson1
# twitter_username: your_username
# linkedin_username: your_username

# Default post settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

# Locale settings
timezone: Asia/Shanghai
lang: en

# Syntax highlighting
highlighter: rouge

# Excluded files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
