title: "Jiajun Liang"
description: "Former QA engineer writing about code, markets, travel, and systems."
url: "https://jackmeson1.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "default"

locale: "en"
timezone: "America/Vancouver"
permalink: /:categories/:year/:month/:day/:title/
paginate: 10
search: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

author:
  name: "Jiajun Liang"
  avatar: "/assets/images/avatar.jpg"
  bio: "Former QA engineer writing about code, markets, travel, and systems."
  location: "Vancouver, BC"


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
